### ISSUE TITLE
ng-mocks peer dependency

### ISSUE THREAD

**Issue by kylecannon** [getsaf/shallow-render#115] opened 2019-06-10 15:54 UTC
ng-mocks is now version 8 which according to the changelog is strictly for angular 8 compatibility. https://github.com/ike18t/ng-mocks/blob/master/CHANGELOG.md 

Currently shallow-render uses 7.8.0, throwing a warning for incorrect peer dependency.

**Comment by getsaf** [comment] 2019-06-11 13:53
Good catch.. I currently have ng-mocks as a dev-dependency which is nice because it allows users to simply "npm install shallow-render" and they're done. Seems that ng-mocks 7.8 had a peer-depencency with Angular set to a maximum of version 7 (even though *it does work with NG8*).

I have a dilemma though, I cannot simply change the package-json to use ng-mocks 8 because that version uses TypeScript 3.4.x and using it would create an incompatibility with NG6 (which uses a maximum of TS 2.9).

The only options I see are:
* Upgrade shallow-render to ng-mocks@8 and deprecate support for NG6. (leaning towards this)
* Ask @ike18t to publish another version of ng-mocks (7.9) that removes the upper-end of the Angular peer-dependency from the package.json.

**Comment by kylecannon** [comment] 2019-06-12 14:50
what if you did `^7.8.0 || ~8.0.0`?

**Comment by getsaf** [comment] 2019-06-14 18:40
I just tried that in a local project and it looks like if you `npm add shallow-render` in an NG6 project, it would install ng-mocks@8 which breaks things.

The issue appears to be that while ng-mocks@8 says it supports Angular 5x-8x, it uses TypeScript version and syntax that isn't compatible with Angular 5, 6x projects because older versions of Angular are locked to older versions of TypeScript.

I kind-of want to see if @ike18t would mind publishing another version of ng-mocks@7x and include NG8x support in the package.json to resolve this. Thoughts @ike18t?

**Comment by ike18t** [comment] 2019-06-14 18:52
The problem is that the method signature for ViewChild and some of the other decorators have changed in ng8 to have a required 2nd argument which is why I went the route of cutting 8 as only 8.

**Comment by getsaf** [comment] 2019-07-13 19:02
I'm gonna have to close this issue. There is no clean solution that maintains compatibility with older versions. My intention is to support all "in support" versions of Angular so I cannot upgrade to ng-mocks@8 without dropping support for NG < 8.

Fortunately, things work just fine, it's just a cosmetic warning.

**Closed by getsaf** 2019-07-13 19:02 UTC
