### ISSUE TITLE
Not working with library input components that have implemented ControlValueAccessor

### ISSUE THREAD

**Issue by Rolandisimo** [getsaf/shallow-render#174] opened 2020-09-08 11:29 UTC
I'm getting this error
```
error properties: Object({ originalStack: 'Error: No value accessor for form control with unspecified name attribute
```
when rendering an external library component that has ControlValueAccessor implemented.
The library components structure is this
```
export class InputComponent extends InputBase<string> {
// and base 
export abstract class InputBase<T> implements ControlValueAccessor {
```

Component is used like this
```
<my-input
  #hexInput
  (input)="onKey(hexInput.value)"
  [(ngModel)]="currentColor"
  [label]="'HEX code'"
  [helperText]="'Please add a valid HEX color'"
  [invalid]="invalidHex"
></my-input>
```
I can fix the issue by adding `ngDefaultControl` attribute but afaik this issue occurs only because the component is not recognized as having implemented ControlValueAccessor.

Can you please assist with this?

**Comment by getsaf** [comment] 2020-09-08 15:10
Yeah, I can probably just solve this by implementing `ControlValueAccessor` in the default [component](https://github.com/getsaf/shallow-render/blob/master/lib/tools/mock-component.ts)/[directive](https://github.com/getsaf/shallow-render/blob/master/lib/tools/mock-directive.ts) mocks. I'll try to get this done today and push a minor release.

**Comment by getsaf** [comment] 2020-09-08 18:22
So I gave this a go and it looks like simply implementing `ControlValueAccessor` on the base component mock is not enough to get past this issue. I'm not totally versed in `ngModel` and `ControlValueAccessor` usage, could you check out this stackBlitz and alter the `ChildInputComponent` in a way that would make the test pass? This way, I can mimic the same behavior on the underlying mock system.

https://stackblitz.com/edit/github-dkal66?file=examples/example.spec.ts

**Comment by Rolandisimo** [comment] 2020-09-08 20:28
I'll give it a go. Thanks

**Comment by Rolandisimo** [comment] 2020-09-08 20:33
Am I missing something? It shows that the test is passing. 🤔

**Comment by getsaf** [comment] 2020-09-09 01:24
Oh, I should have mentioned that it is passing because of the ngDefaultControl directive. That was the only way I could make it pass but I don't know how to make it work without it.

**Comment by Humberd** [comment] 2020-09-11 12:13
Ok, so we managed to do a workaround in our app. We have around 1300 test files and manually adding `ngDefaultControl` wasn't even an option. Here is our solution:

```typescript
import { Directive, NgModule } from '@angular/core';
import { DefaultValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';
import { Shallow } from 'shallow-render';

@Directive({
    // tslint:disable-next-line:directive-selector
    selector: '[formControl], [formControlName], [ngModel]',
    providers: [
        {
            provide: NG_VALUE_ACCESSOR,
            useExisting: Angular10ShallowCompatibilityDirective,
            multi: true,
        },
    ],
})
class Angular10ShallowCompatibilityDirective extends DefaultValueAccessor {}

@NgModule({
    declarations: [Angular10ShallowCompatibilityDirective],
    exports: [Angular10ShallowCompatibilityDirective],
})
class Angular10ShallowCompatibilityModdule {}

export function shallowSupportForAngular10(): void {
    Shallow.alwaysImport(Angular10ShallowCompatibilityModdule);
    Shallow.neverMock(Angular10ShallowCompatibilityDirective);
}
```

The `shallowSupportForAngular10` should be added in the main test entry point. In our case it was `setup-jest.ts`

```
// setup-jest.ts
...
shallowSupportForAngular10();
...
```

**Comment by getsaf** [comment] 2020-09-11 12:37
Awesome, thanks for the write-up and the description. Based on your description, I think I can do this automatically by detecting when a component being mocked provides `NG_VALUE_ACCESSOR` and add it to the mock too.

I'll try to get this in today and let you know when it's ready.

**Comment by getsaf** [comment] 2020-09-11 17:47
Aright, so I have given it a go with a PR but I'm not satisfied that it's the right approach. I am trying my best to avoid writing code that has an `if thing === NG_VALUE_ACCESSOR` to avoid being too brittle and it turns out that a new feature to Shallow will make this fix much easier.

Two issues here:

1. We currently ignore component/directive-level providers. This will be fixed so they will run through the standard mocking mechanism.

2. We currently do not have any way to mock a provider by providing another class instance which is a functional gap in what Shallow offers vs what Angular allows us to do with InjectionTokens.

I won't have time to finish this work today, but I think I'll end up just adding support for this and then it'll be easy to replace the NG_VAULE_ACCESSOR directive manually...

New feature would be:
`shallow.replaceProvider(provider: Provider, replacement: Provider);`
and
`Shallow.alwaysReplaceProvider(provider: Provider, replacement: Provider);`


It would be used like this:
```ts
shallow.replaceProvider(NG_VALUE_ACCESSOR, {provide: NG_VALUE_ACCESSOR, useClass: DefaultValueAccessor});
```

I will be out of town for the weekend, but I'll get this in on Monday for sure.

**Comment by getsaf** [comment] 2020-09-14 23:19
Ok, here's the final result: #175 
I've published this as a pre-release so to install it, you'll have to be specific when upgrading:

```sh
npm i -D shallow-render@10.1.0-0
```

I realized that Shallow already has a way to handle manual provider mocks so your fix should be one of the following:

### Always use `DefaultValueAccessor` in your test
```ts
shallow.provideMock({provide: NG_VALUE_ACCESSOR, useClass: DefaultValueAccessor});
```

### Avoid mocking and use whatever accessor is specified by the mocked component
```ts
shallow.dontMock(NG_VALUE_ACCESSOR);
```

### Globally force the use of `DefaultValueAccessor`
```ts
Shallow.alwaysProvide({provide: NG_VALUE_ACCESSOR, useClass: DefaultValueAccessor})
  .dontMock(NG_VALUE_ACCESSOR);
```

### Globally avoid mocking
```ts
Shallow.neverMock(NG_VALUE_ACCESSOR);
```

Please give it a go and let me know how it works for you.

**Comment by Rolandisimo** [comment] 2020-09-15 08:30
Thanks. Will try it and get back to you. 🙁

**Comment by Rolandisimo** [comment] 2020-09-17 10:57
I installed `npm i -D shallow-render@10.1.0-0`

@getsaf Unfortunately, with every combination I get the following error:
`TypeError: dir.valueAccessor.writeValue is not a function`

Is there something I'm missing?

**Comment by getsaf** [comment] 2020-09-18 14:04
It might be due to the base mocks not implementing `ControlValueAccessor` but in my testing, that wasn't necessary.

I just added a commit and pushed 10.1.0-2, give it a try and see if that resolves the issue.

**Comment by Rolandisimo** [comment] 2020-09-18 14:29
Fantastic work! Thanks @getsaf. I haven't extensively tested but I can now render components with ControlValueAccessor without even doing the mocking you mentioned here https://github.com/getsaf/shallow-render/issues/174#issuecomment-692368521

**Comment by getsaf** [comment] 2020-09-18 14:45
Hell yeah! Glad this worked out. I had been meaning to tackle component-level providers for a while but it hadn't given anyone any trouble until you mentioned it.

Thanks for reporting. I'll get a proper 10.1.0 release out soon and update the docs.

**Comment by getsaf** [comment] 2020-09-22 23:09
Hey @Rolandisimo, needed to mention that there was an important regression fix in the 10.1.1 bugfix release. It turns out that the reason you didn't have to do any of the fixes I mentioned above was due to a bug.
Once upgrading to [v10.1.1](https://github.com/getsaf/shallow-render/releases/tag/v10.1.1), you will likely need to implement one of those fixes above. 

If you don't mind reporting back your findings when you have time. No rush, but I'm going to leave this issue open until I hear back from you.

**Comment by Rolandisimo** [comment] 2020-09-23 06:56
Will check. Thanks for pointing it out

**Comment by livia-e** [comment] 2020-09-24 13:53
Hello, I have the similar problem as in the description. I am using formControlName so my error is referenced to that 'Error: No value accessor for form control with name: 'language'
I have a form with lots of different fields, the problem only happens with the mat-select.
I created a small demo project to present it as well https://stackblitz.com/edit/angular-59x3nl-krwuv3?
Is it possible to fix it without complicated workaround?
Thank you in advance for your help

**Comment by getsaf** [comment] 2020-09-24 16:54
@livia-e, This is pretty strange, I'm looking at the [code for mat-select and it [does not provide](https://github.com/angular/components/blob/master/src/material/select/select.ts#L1136-L1137) `NG_VALUE_ACCESSOR`.

I am digging in a little further to see if I can understand how it works and will report back.

**Comment by efux** [comment] 2020-09-24 17:20
> I am digging in a little further to see if I can understand how it works and will report back.
Have a look at the constructor of the mat-select. They inject the NgControl with @Self and set the valueAccessor to this:
https://github.com/angular/components/blob/master/src/material/select/select.ts#L497
Apparently this is done to prevent a circular dependency.

**Comment by getsaf** [comment] 2020-09-24 18:06
Thanks for that tip @efux, you just saved me a lot of time.

My first thought is that this sucks because I don't know of another way to get around that hack except to force all mocks to provide `NG_VALUE_ACCESSOR` even if the underlying component does not provide one.

I may just end-up doing that if it comes down to it. I was hoping to avoid the need to special-case certain libraries in Shallow-Render but without a fix for this, it becomes very difficult to test with forms.

**Comment by getsaf** [comment] 2020-09-24 19:40
Alright, I think we have everyone covered now.

Can everyone try shallow-render@10.1.2 and the final result is that there is no need for the provider/mock  "workarounds" for forms.

I ended up caving in and building in a work-around just for angular/material's weird injection magic. The two main changes are:
* Shallow will never mock `NG_VALUE_ACCESSOR` by default.
* If a mocked component is used with a directive that extends `NgControl` (like material inputs), if the component does not provide an `NG_VALUE_ACCESSOR` explicitly, a dummy one will be provided automatically.

**Comment by livia-e** [comment] 2020-09-25 06:44
Thank you for the fix. It works fine for me.

**Closed** 2020-09-28 12:55 UTC
