### ISSUE TITLE
Problems with HttpClientTestingModule?

### ISSUE THREAD

**Issue by pheinicke** [getsaf/shallow-render#195] opened 2021-01-04 12:54 UTC
Hi! I didn't want to hijack #194, but this might have similar causes. I'm trying to convert my existing service tests to use shallow-render. The first test is already giving my trouble though.

I want to test a service "ApiService" with method sending a post request:

```
@Injectable({
    providedIn: 'root'
})
export class ApiService {
    constructor(private http: HttpClient) {}

    testMe<T>(url: string): Observable<T> {
        return this.http.post<T>(url, {});
    }
}
```

My old, regular test is working fine:

```
it('should send post request', (done: DoneCallback) => {
    const service: ApiService = TestBed.inject(ApiService);
    const url = '/foo/bar';

    httpMock = TestBed.inject(HttpTestingController);

    service.testMe<unknown>(url).subscribe(() => {
        done();
    });
    const req = httpMock.expectOne(url);
    req.flush({});
});
```

The new test using shallow-render does not work however.

```
describe('ApiService', () => {
    let httpMock: HttpTestingController;
    let service: ApiService;

    beforeEach(() => {
        const shallow: Shallow<ApiService> = new Shallow(ApiService, ApiModule);
        const { instance, inject } = shallow
            .replaceModule(HttpClientModule, HttpClientTestingModule)
            .dontMock(HttpClientTestingModule)
            .createService();
        service = instance;
        httpMock = inject(HttpTestingController);
    });

    afterEach(() => {
        httpMock.verify();
    });

    it('should send post request', (done: DoneCallback) => {
        const url = '/foo/bar';
        service.testMe<unknown>(url).subscribe(() => {
            done();
        });
        const req = httpMock.expectOne(url);
        req.flush({});
    });
});
```

It fails with the error `Error: Expected one matching request for criteria "Match URL: /foo/bar", found none.`
As you can see, the actual test method is exactly the same, so there must be setup problems. Maybe something is mocked that shouldn't be?

Do you have any idea what might be causing this?

Thank you!

**Comment by getsaf** [comment] 2021-01-04 14:22
That test passes just fine when I put it into StackBlitz. Did I copy something incorrectly there?

https://stackblitz.com/edit/github-3wajlf?file=examples/service-only-testing.spec.ts

**Comment by pheinicke** [comment] 2021-01-05 13:40
Thanks for your quick reply.

This is very weird. If I somehow messed up my module/test setup, I would expect to get a "Could not find class HttpClient. Did you forget to import a module?" error instead.

I'll let you know if I find anything.

**Comment by getsaf** [comment] 2021-02-04 14:09
Hey, checking back in. Any updates on this? Was it a missing "import" for the `HttpClientModule` in the `ApiModule`?

**Comment by pheinicke** [comment] 2021-02-05 11:07
Hey! No updates so far. I was pretty busy with other stuff and had to put this issue aside for a while. But I got a day or two now, so I will investigate further. 
A missing import does not appear to be the issue.

**Comment by pheinicke** [comment] 2021-02-05 11:19
Huh, fresh eyes on the problem or whatever, but I just got the test to run.

My ApiModule imports a SharedModule, which in turn provides HttpClientModule and a bunch of other modules. This SharedModule is imported by almost every other module I have in the app.

The tests work, if I only import HttpClientModule in the ApiModule, and remove the SharedModule. Importing both of them does not work, importing only SharedModule does not work.

If I'm telling shallow not to mock the SharedModule, I get "No provider for HttpTestingController", even if I call ".replaceModule(HttpClientModule, HttpClientTestingModule)".

**Comment by getsaf** [comment] 2021-02-05 13:06
Good to hear you got it working. This does sound like what I would expect from the module system. From my understanding of the module system, to gain access to an injectable, a module must import another module that explicitly lists the injectable in the `providers` property of `@NgModule` configuration.

Since your `SharedModule` simply `imports` the `HttpClientModule`, it does not `provide` the `HttpClient` to the outside world. This means the `SharedModule` will have access to `HttpClientModule`'s providers, but they are contained inside the `SharedModule`.

Anyway, thanks for getting back to me, I'm going to close this issue.

**Comment by pheinicke** [comment] 2021-02-08 08:51
To be honest, I would expect the tests to be working with the SharedModule (like the "vanilla" angular tests do). The SharedModule does not simply import HttpClientModule, it also exports it. So it does provide the HttpClient to everyone importing it.

**Comment by getsaf** [comment] 2021-02-12 22:11
Oh, I didn't realize that you were also exporting the HttpClientModule from your shared module. That does seem like a problem. I looked through the code to see if I could find anything that stands out as an issue and didn't see anything but I'll re-open this issue as a reminder to dig in and see if I can reproduce this by exporting a module from a shared module.

**Comment by getsaf** [comment] 2023-02-11 22:11
Trying to close out as many issues as I can lately. I tried creating a test with a module that exports HttpClientModule which is then used in the actual module under test.

Tried with NG12 (shallow-render@12.0.0) and with the latest v15.

This is my test which sounds like it mirrors your scenario. It all works just fine.
([example stackblitz](https://stackblitz.com/edit/github-3wajlf-w58fvo?file=examples%2Fservice-only-testing.spec.ts%3AL33))

Could you give this a once-over to see if it lines up with your issue?

```ts
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { HttpClientTestingModule, HttpTestingController } from '@angular/common/http/testing';
import { Component, NgModule, OnInit } from '@angular/core';
import { Shallow } from 'shallow-render';

////// Module Setup //////
@Component({
  selector: 'my-component',
  template: '<label>{{labelText}}</label>',
})
class MyComponent implements OnInit {
  labelText?: string;

  constructor(private _httpClient: HttpClient) {}
  async ngOnInit() {
    this.labelText = await this._httpClient
      .get<string>('/foo/as/a/service')
      .toPromise()
      .catch(() => 'ERROR');
  }
}

@NgModule({
  imports: [HttpClientModule],
  exports: [HttpClientModule],
})
class OnlyExportsHttpClientModule {}

@NgModule({
  imports: [OnlyExportsHttpClientModule],
  declarations: [MyComponent],
})
class MyModule {}
//////////////////////////

describe('using replaceModule', () => {
  let shallow: Shallow<MyComponent>;

  beforeEach(() => {
    shallow = new Shallow(MyComponent, MyModule).replaceModule(HttpClientModule, HttpClientTestingModule);
  });

  it('displays the response from the foo service', async () => {
    const { element, inject, fixture } = await shallow.render();
    const client = inject(HttpTestingController);
    client.expectOne('/foo/as/a/service').flush('foo response');
    await new Promise(resolve => setTimeout(resolve, 1));
    fixture.detectChanges();

    expect(element.nativeElement.textContent).toBe('foo response');
  });

  it('displays ERROR when a service error occurs', async () => {
    const { element, inject, fixture } = await shallow.render();
    const client = inject(HttpTestingController);
    client.expectOne('/foo/as/a/service').error(new ErrorEvent('BOOM'));
    await new Promise(resolve => setTimeout(resolve, 1));
    fixture.detectChanges();

    expect(element.nativeElement.textContent).toBe('ERROR');
  });
});
```

**Comment by getsaf** [comment] 2024-02-01 01:32
Closed due to inacivity

**Closed by getsaf** 2024-02-01 01:32 UTC
